# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  hardware.facter = {
    enable = true;
    reportPath = ./facter.json;
  };
  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "thunderbolt"
        "nvme"
        "usb_storage"
        "sd_mod"
      ];
      kernelModules = [ "xe" ];
      systemd.enable = true;
    };
    kernelModules = [
      "kvm-intel"
      "asus_wmi"
      "asus_nb_wmi"
      "zstd"
      "zsmalloc"
      "hid_apple"
    ];
    kernelParams = [
      "xe.force_probe=7d55"
      "xe.enable_psr=1"
      "intel_idle.max_cstate=9"
      "i915.force_probe=!7d55"
    ];

    zswap = {
      enable = true;
      compressor = "zstd";
      zpool = "zsmalloc";
      maxPoolPercent = 40;
    };

    kernel.sysctl = {
      "vm.swappiness" = 30;
      "vm.watermark_scale_factor" = 125;
      "vm.watermark_boost_factor" = 0;
      "vm.page-cluster" = 0;
    };

    extraModprobeConfig = ''
      options hid_apple fnmode=2
    '';

    extraModulePackages = [ ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/3d5ffee0-2cd5-4763-b71c-f13d3856d2bc";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/3d5ffee0-2cd5-4763-b71c-f13d3856d2bc";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/AC99-089E";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/c88b5863-8caa-4fcf-9a41-1c82f8112946"; }
  ];

  fileSystems."/mnt/hdd" = {
    device = "/dev/disk/by-uuid/748C0F7E8C0F3A5E";
    fsType = "ntfs";
    options = [
      "nofail"
      "defaults"
      "uid=1000"
      "gid=100"
      "umask=0022"
      "locale=en_US.utf8"
    ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware = {
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

    graphics = {
      enable = true;
      enable32Bit = true;
      extraPackages = with pkgs; [
        vpl-gpu-rt
        intel-media-driver
        intel-compute-runtime
      ];
    };
  };
}
