# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "thunderbolt"
        "nvme"
        "usb_storage"
        "sd_mod"
        "usbhid"
        "ahci"
      ];
      kernelModules = [ "xe" ];
      systemd.enable = true;
    };
    kernelModules = [
      "kvm-intel"
      "zstd"
      "zsmalloc"
      "hid_apple"
    ];
    kernelParams = [
      "xe.force_probe=7d55"
      "xe.enable_psr=1"
      "i915.force_probe=!7d55"
    ];

    zswap = {
      enable = true;
      compressor = "zstd";
      zpool = "zsmalloc";
      maxPoolPercent = 50;
    };

    kernel.sysctl = {
      "vm.swappiness" = 50;
      "vm.watermark_scale_factor" = 125;
      "vm.watermark_boost_factor" = 0;
      "vm.page-cluster" = 0;
    };

    extraModprobeConfig = ''
      options hid_apple fnmode=2
    '';

    extraModulePackages = [ ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/76382d2d-79fa-4470-b0ab-af180a5f4010";
    fsType = "btrfs";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/76382d2d-79fa-4470-b0ab-af180a5f4010";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/76382d2d-79fa-4470-b0ab-af180a5f4010";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/A0A2-4E6F";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/830c9dcf-5b32-40c5-a07a-30da9a8700d6"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware = {
    cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

    graphics = {
      enable = true;
      enable32Bit = true;
      extraPackages = with pkgs; [
        vpl-gpu-rt
        intel-media-driver
        intel-compute-runtime
      ];
    };

    bluetooth = {
      enable = true;
      powerOnBoot = true;
    };
  };
}
